### ISSUE TITLE
My Idea 💡 

### ISSUE THREAD

**Issue by CoderUsman** [atoms19/ligo.css#1]
Hello @atoms19,
I have an idea for your repo so it will be easily available.

Make a page for your repo like:

atoms19.github.io/ligo.css

Hope you'll work on my idea.
Happy Coding 😊 😃

**Comment by atoms19** [comment]
thanks for reminding me i actually wanted to make something like that
i did actually (its in the my github.io repo)

it looks pathetic right now and the documentation isn't very clear aswell
so i was thinking of remaking the whole site from scratch making it look
prettier and more informative

i kinda got busy with other things so i forgot about it  I'll make it soon
as my exams finishes (may 17th)

thanks for reaching out 😄

**Comment by atoms19** [comment]
sry lol ,i got confused with my other framework ilus , I haven't actually
even thought about making a proper site for ligo

thank you soo much for the idea actually, I am very busy as i said with
school work lol

I plan on improving ligo and adding a few more features like a proper
responsive grid etc
I'll make a site for at soon as i get time

thanks again :)

**Comment by CoderUsman** [comment]
Thank you so much for considering my suggestion 😇
