### ISSUE TITLE
@atoms19

### ISSUE THREAD

**Issue by CoderUsman** [atoms19/ligo.css#2]
Hi @atoms19,
I just wanted to ask a question.
How did you made a cdn.jsdelivr link?

I want to make it in my repo.

😊😊😊

**Comment by atoms19** [comment]
ooh its easy just substitute the contents in {}

https://cdn.jsdelivr.net/gh/{your username}/{repo name}/{file.name}

**Comment by CoderUsman** [comment]
Thank you so much, you're so helplful!
